version: "3.4"

networks:
  default:
    driver: bridge

services:
  api:
    build: .
    networks:
      - default
    volumes:
      - ./src:/src
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000", "--reload"]
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env